name: colorracer2
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  # current dart sdk version : 2.8.0
  #sdk: 2.14.0 # Because colorracer2 requires SDK version 2.14.0, version solving failed
  sdk: ">=2.4.9 <3.0.0"
  # min dart sdk for flame 0.29.4
  # sdk: 2.3.0
  #sdk: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter

  #latest flame version : 0.29.4
  flame: ^0.29.4 # Android resource linking failed : resource android:attr/lStar not found.
  # to work around the issue, modify .dart_tool/package.config.json, removing audioplayers

  # flame: ^0.29.1 # lStar continues
  # flame: ^0.29.0 # lStar continues , depends on audioplayer 17.1
  # flame: ^0.28.0 # depends on audioplayer 15.1

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.3

  # audioplayers: ^0.18.3  # latest : gives lStar missing error.
  # audioplayers: ^0.16.1  # to work with flame 29.1
  # audioplayers: ^0.17.1  # to work with flame 29.0
  # audioplayers: ^0.16.1  # to avoid errors.
  # audioplayers: ^0.15.1  # to work with flame 28.0
  # 0.15.1 gives error :
  #  The plugin `audioplayers` uses a deprecated version of the Android embedding.
  #  To avoid unexpected runtime failures, or future build failures, try to see if this plugin supports the Android V2 embedding. Otherwise, consider removing it since a future release of Flutter will remove these deprecated APIs.


dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
